#ifndef NXDK_LOW_LEVEL_NV2A_TESTS_M2MF_TEST_COMMON_H
#define NXDK_LOW_LEVEL_NV2A_TESTS_M2MF_TEST_COMMON_H

#include <cstddef>
#include <cstdint>
#include <deque>
#include <string>

#include "logger.h"
#include "nv2astate.h"
#include "pushbuffer.h"
#include "third_party/gpu_m2m.h"

void LogMsg(const char* fmt, ...);
const std::deque<std::string>& GetOnScreenLog();
void ClearOnScreenLog();

#ifndef MAXRAM
#define MAXRAM 0x03FFAFFF
#endif

constexpr uint32_t kMaxRam = MAXRAM;

//! Re-export pbkitplusplus definitions for convenience
using PBKitPlusPlus::kM2MDmaInChannel;
using PBKitPlusPlus::kM2MDmaNotifyChannel;
using PBKitPlusPlus::kM2MDmaNotifyScratchChannel;
using PBKitPlusPlus::kM2MDmaOutChannel;
using PBKitPlusPlus::kM2MSubchannel;

static inline void PBKitBusyWait() {
  PBKitPlusPlus::NV2AState::PBKitBusyWait();
}

//! NV_MEMORY_TO_MEMORY_FORMAT_FORMAT configuration:
//! Bits [7:0]   INPUT_INC  = 1 byte
//! Bits [15:8]  OUTPUT_INC = 1 byte
constexpr uint32_t kM2MFFormatLinearByteStream = 0x0101;

//! NV_MEMORY_TO_MEMORY_FORMAT_BUF_NOTIFY value to trigger the transfer
constexpr uint32_t kM2MFBufferNotifyKick = 0;

//! Initializes M2MF engine using pbkitplusplus.
bool M2MFInit();

//! Tears down / awaits M2MF completion.
void M2MFTeardown();

//! Resolves physical memory address from a virtual address pointer.
uint32_t M2MFGetPhysicalAddress(const void* p);

//! Fills a memory buffer with a deterministic test pattern.
void M2MFFillPattern(void* buf, size_t size, uint8_t seed = 0xA5);

//! Verifies a buffer matches the pattern generated by M2MFFillPattern.
bool M2MFVerifyPattern(const void* buf, size_t size, uint8_t seed = 0xA5);

//! Verifies all bytes in a buffer equal the specified canary value.
bool M2MFVerifyCanaries(const void* buf, size_t size, uint8_t canary = 0x55);

#endif  // NXDK_LOW_LEVEL_NV2A_TESTS_M2MF_TEST_COMMON_H
